name: flutter_signature_pad
description: Flutter widget to allow users to sign with finger and export the result as image.
version: 2.0.3
homepage: https://github.com/kiwi-bop/flutter_signature_pad.git

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

environment:
    sdk: ">=2.1.0 <3.0.0"

